### ISSUE TITLE
[META] Follow-up to #975: isolate CUDA/PyTorch runtime compatibility before broad GPU validation

### ISSUE THREAD

**Issue by superAngGao** [tile-ai/TileOPs#980]
Follow-up to #975.

This issue is separate from the TileLang API migration tracked in #979.

## Problem

Broad GPU validation is currently blocked by a CUDA/PyTorch runtime compatibility problem in the local upgraded environment.

This does **not** look like a TileLang API break by itself.

During the per-test-file sweep, the message

`The NVIDIA driver on your system is too old (found version 12090)`

appeared in `75` test-file logs.

Of those:

- `66` test files failed with this runtime error on the path to `torch.cuda.get_device_capability()` / CUDA init
- `9` additional test files still passed, but their logs also contained the same warning string

## Affected failing test files

- `tests/ops/attention/test_mean_pooling.py`
- `tests/ops/attention/test_mha.py`
- `tests/ops/attention/test_mha_decode.py`
- `tests/ops/attention/test_mha_decode_paged.py`
- `tests/ops/test_activation.py`
- `tests/ops/test_ada_layer_norm.py`
- `tests/ops/test_ada_layer_norm_zero.py`
- `tests/ops/test_argreduce.py`
- `tests/ops/test_batch_norm.py`
- `tests/ops/test_binary_arith.py`
- `tests/ops/test_bitwise.py`
- `tests/ops/test_comparison.py`
- `tests/ops/test_convolution.py`
- `tests/ops/test_cumulative.py`
- `tests/ops/test_deltanet_chunkwise_bwd.py`
- `tests/ops/test_deltanet_fwd.py`
- `tests/ops/test_deltanet_recurrence.py`
- `tests/ops/test_dropout.py`
- `tests/ops/test_elementwise_caching_autotune.py`
- `tests/ops/test_elementwise_compile.py`
- `tests/ops/test_elementwise_fp8.py`
- `tests/ops/test_elementwise_independent_fp8.py`
- `tests/ops/test_engram.py`
- `tests/ops/test_fft.py`
- `tests/ops/test_fp8_lighting_indexer.py`
- `tests/ops/test_fp8_quant.py`
- `tests/ops/test_fused_add_layer_norm.py`
- `tests/ops/test_fused_add_rms_norm.py`
- `tests/ops/test_fused_gated.py`
- `tests/ops/test_gated_deltanet_chunkwise_bwd.py`
- `tests/ops/test_gated_deltanet_fwd.py`
- `tests/ops/test_gated_deltanet_recurrence.py`
- `tests/ops/test_gemm.py`
- `tests/ops/test_gla_chunkwise_bwd.py`
- `tests/ops/test_gla_chunkwise_fwd.py`
- `tests/ops/test_gla_recurrence.py`
- `tests/ops/test_group_norm.py`
- `tests/ops/test_grouped_gemm.py`
- `tests/ops/test_instance_norm.py`
- `tests/ops/test_layer_norm.py`
- `tests/ops/test_logical.py`
- `tests/ops/test_logical_reduce.py`
- `tests/ops/test_mamba.py`
- `tests/ops/test_mhc_post.py`
- `tests/ops/test_mhc_pre.py`
- `tests/ops/test_moe_fused_moe.py`
- `tests/ops/test_moe_fused_topk.py`
- `tests/ops/test_moe_permute.py`
- `tests/ops/test_moe_permute_align.py`
- `tests/ops/test_moe_shared_fused_moe.py`
- `tests/ops/test_moe_unpermute.py`
- `tests/ops/test_norm_ops.py`
- `tests/ops/test_pool.py`
- `tests/ops/test_reduce.py`
- `tests/ops/test_reduce_dim_none.py`
- `tests/ops/test_reduce_multidim.py`
- `tests/ops/test_rms_norm.py`
- `tests/ops/test_rope.py`
- `tests/ops/test_softmax.py`
- `tests/ops/test_special_elementwise.py`
- `tests/ops/test_topk_selector.py`
- `tests/ops/test_unary_math.py`
- `tests/ops/test_vector_norm.py`
- `tests/ops/test_welford_non_aligned.py`
- `tests/test_autotune.py`
- `tests/test_compile.py`

## Environment observations

In the current local upgraded env:

- `torch==2.11.0+cu130`
- `torch.version.cuda == 13.0`
- `torch.cuda.device_count() == 8`
- `torch.cuda.is_available() == False`
- `torch.cuda.get_device_capability()` raises the `found version 12090` runtime error

At the same time, the host reports:

- `nvidia-smi` driver `575.57.08`
- GPU: `NVIDIA H200`

The environment also appears to contain a mixed set of CUDA 12 and CUDA 13 Python packages, for example both:

- `nvidia-cuda-runtime-cu12==12.8.90`
- `nvidia-cuda-runtime==13.0.96`
- `nvidia-cudnn-cu12==9.10.2.21`
- `nvidia-cudnn-cu13==9.19.0.56`
- `nvidia-nccl-cu12==2.27.5`
- `nvidia-nccl-cu13==2.28.9`

This suggests the current env is not a clean, single-runtime CUDA stack.

## Why this matters

Until this runtime issue is resolved, full-suite results are hard to interpret:

- many operator failures are likely environment-induced rather than TileOPs bugs
- this masks the narrower TileLang API migration work tracked in #979

## Likely interpretation

Upgrading the user-space CUDA toolkit alone is unlikely to be sufficient.

This looks more like one of the following:

1. `torch==2.11.0+cu130` is too new for the effective CUDA driver compatibility exposed to the process
2. the env is mixing incompatible CUDA 12 / CUDA 13 runtime wheels
3. the intended official test env needs a stricter PyTorch/CUDA pin rather than floating to the newest runtime stack

## Suggested next steps

1. define the intended official GPU test stack for post-#975 validation
2. ensure the env uses a single coherent CUDA runtime family
3. verify whether the target machines are meant to support `cu130`, or whether TileOPs should stay on a `cu12x` PyTorch build for now
4. re-run broad GPU validation only after the runtime stack is cleaned up

## Acceptance criteria

- `torch.cuda.is_available()` is `True` in the intended upgraded env
- `torch.cuda.get_device_capability()` succeeds without driver/runtime errors
- broad GPU test failures are no longer dominated by `found version 12090`
- full-suite results can then be interpreted separately from #979

**Comment by superAngGao** [comment]
Related note: broad GPU-test instability here is not explained by runtime compatibility alone.

There is a separate TileLang-side source-compatibility thread in #979. Recent TileLang commits changed not only the public GEMM API (`T.gemm(..., wg_wait=...)` -> synchronous `T.gemm(...)` plus explicit `T.wgmma_gemm(...)` / `T.wait_wgmma(...)`), but also pipeline rewriting, ThreadSync placement, and canonical GEMM lowering.

That means the current full-test failure surface is likely a mix of:

- runtime-stack incompatibility tracked in this issue
- TileOPs source migration work tracked in #979

So even after this runtime issue is resolved, the TileLang-side kernel migration still needs to happen before `#975` can be considered complete.

**Comment by superAngGao** [comment]
Update from local env cleanup / re-validation.

I rebuilt a fresh local GPU test env without the previously mixed CUDA 12 / CUDA 13 runtime stack.

## Current validated local env

Local env path:

- `/home/ga/TileOPs-issue975/.venv-cu128`

Key properties:

- Python `3.12`
- `tilelang 0.1.8+cuda.git5f70374c`
- `torch 2.9.1+cu128`
- `tileops` installed editable from the current upstream clone at `/home/ga/TileOPs-issue975`

Runtime sanity checks in this env:

- `torch.cuda.is_available() == True`
- `torch.cuda.get_device_capability() == (9, 0)`
- GPU target is Hopper (`H200`)

## Validation results in the cleaned env

The previous

- `The NVIDIA driver on your system is too old (found version 12090)`

error is no longer reproduced in this cleaned `cu128` env.

Two quick probes both pass:

- `tests/test_compile.py` -> `3 passed`
- `tests/ops/test_activation.py -x` -> `52 passed`

Notably, `test_activation.py` was one of the files that previously failed very early with the `found version 12090` runtime error.

## Revised interpretation

This strongly suggests the broad `driver too old` failure bucket was primarily caused by the polluted local env, not by the host driver itself.

The problematic env had drifted to something closer to:

- `torch 2.11.0+cu130`
- mixed `cu12` and `cu13` NVIDIA Python packages in the same env
- `torch.cuda.is_available() == False`

By contrast, the cleaned `cu128` env works as expected on the same machine.

## Practical takeaway

For post-#975 GPU validation, the immediate priority should be:

1. keep the runtime stack on a clean, coherent `cu128` family
2. avoid mixing `cu12` and `cu13` packages in the same env
3. separate runtime-stack failures from the TileLang / TileOPs source-migration work tracked in #979

I have not yet forced this cleaned env to `torch 2.10.0+cu128`; the current `2.9.1+cu128` baseline was sufficient to prove that the earlier `driver too old` failures were environmental rather than a true host-driver limitation.

**Comment by superAngGao** [comment]
Update from local environment isolation work on 2026-04-17.

We now have a clean working CUDA 12.8 test environment that avoids the `torch==2.11.0+cu130` / mixed-runtime problem described in this issue.

Working stack
- Python 3.12.12
- torch==2.10.0+cu128
- torch.version.cuda == 12.8
- tilelang==0.1.8
- apache-tvm-ffi==0.1.8.post2
- triton==3.6.0
- ninja==1.13.0

Important installation detail
- `tilelang==0.1.8` was installed with `--no-deps`
- reason: the default dependency resolution path tried to pull in `torch==2.11.0` and the CUDA 13 runtime family
- to keep the env on the intended CUDA 12.8 stack, we installed in this order:
  1. `torch==2.10.0` from `https://download.pytorch.org/whl/cu128`
  2. supporting non-torch deps: `apache-tvm-ffi==0.1.8.post2`, `cloudpickle`, `ml-dtypes`, `numpy`, `psutil`, `tqdm`, `z3-solver==4.15.4.0`, `torch-c-dlpack-ext`, `einops`, `pyyaml`, plus dev tools
  3. `pip install tilelang==0.1.8 --no-deps`
  4. `pip install -e . --no-deps`

Validation results in the new env
- `torch.cuda.is_available() == True`
- `torch.cuda.device_count() == 8`
- `torch.cuda.get_device_capability() == (9, 0)` on H200
- package set is a clean CUDA 12 family (`nvidia-*-cu12` only in the torch runtime path)

Tests that passed in this env
- `python -m pytest tests/test_compile.py -q` -> `3 passed`
- `python -m pytest tests/ops/test_gemm.py -q -k 'smoke-fp16-square'` -> `1 passed`

Interpretation
- the `found version 12090` runtime problem from this issue is no longer reproducing in this env
- `torch 2.10 + cu128` is a viable candidate official validation stack for continued GPU testing

Next step on my side
- clone a fresh upstream working tree
- recreate the same env there
- run the full test suite from the clean clone so that broader results are not contaminated by the old local upgraded env

**Comment by superAngGao** [comment]
Follow-up with a full clean-clone validation result on 2026-04-17.

We re-ran the environment isolation work from a fresh upstream clone instead of the existing local worktree.

Fresh clone used for validation
- repo: `https://github.com/tile-ai/TileOPs`
- branch: `main`
- commit: `c39d65d31ea3cbd12261d55827ee81fc387dd174`

Environment details
- Python: `3.12.12`
- torch: `2.10.0+cu128`
- `torch.version.cuda == 12.8`
- tilelang: `0.1.8`
- apache-tvm-ffi: `0.1.8.post2`
- triton: `3.6.0`
- torch-c-dlpack-ext: `0.1.5`
- ninja: `1.13.0`

Why this install order matters
- allowing normal dependency resolution for `tilelang==0.1.8` tried to pull in `torch==2.11.0` and the CUDA 13 runtime family
- to keep a clean CUDA 12.8 runtime stack, we had to install `tilelang` with `--no-deps`

Install procedure that worked
```bash
python3.12 -m venv .venv-cu128-t210
source .venv-cu128-t210/bin/activate
python -m pip install -U pip setuptools wheel ninja packaging
python -m pip install torch==2.10.0 --index-url https://download.pytorch.org/whl/cu128
python -m pip install \
  apache-tvm-ffi==0.1.8.post2 \
  cloudpickle ml-dtypes numpy psutil tqdm \
  z3-solver==4.15.4.0 \
  torch-c-dlpack-ext \
  einops pyyaml \
  pytest pytest-xdist \
  ruff==0.14.13 codespell==2.4.1 pre-commit
python -m pip install tilelang==0.1.8 --no-deps
python -m pip install -e . --no-deps
```

Observed runtime state in the clean env
- `torch.cuda.is_available() == True`
- `torch.cuda.device_count() == 8`
- `torch.cuda.get_device_capability() == (9, 0)`
- host GPU: `NVIDIA H200`
- host driver: `575.57.08`
- package set stayed in the CUDA 12 family for the PyTorch runtime path (`nvidia-*-cu12` only; no mixed cu12/cu13 runtime set)

Additional note
- full-suite execution used `TMPDIR=$PWD/.tmp` to avoid unrelated `/tmp` permission/debug-tempdir interference during TileLang/TVM compilation

Validation results in this clean clone
- `python -m pytest tests/test_compile.py -q` -> `3 passed`
- `python -m pytest tests/ops/test_gemm.py -q -k 'smoke-fp16-square'` -> `1 passed`
- full suite:
  - command: `TMPDIR=$PWD/.tmp python -m pytest -q tests`
  - result: `2247 passed, 22 skipped, 16 warnings in 8479.83s (2:21:19)`

Interpretation
- the environment described in this issue is now reproducibly clean and compatible for broad GPU validation
- the original `found version 12090` CUDA/PyTorch runtime issue does not reproduce in this stack
- `torch 2.10.0+cu128` is a strong candidate for the intended official post-#975 GPU validation environment

**Comment by superAngGao** [comment]
Correction to the previous comment: the earlier full-suite result was run against the published `tilelang==0.1.8` wheel, not the intended pinned TileLang commit.

The intended TileLang commit for this validation thread is:
- `ded6a992218a5ec0dbb490128cb21aae7794cdb8`
- subject: `[Feature] Add Producer-Consumer Warp Specialization and T.tma_copy() API (#1909)`

What was wrong before
- I previously reported the environment as if TileLang had been commit-pinned during the full-suite run
- that was inaccurate
- the clean-clone full-suite result (`2247 passed, 22 skipped`) should be interpreted as:
  - `torch==2.10.0+cu128`
  - `tilelang==0.1.8` release wheel
  - not the `ded6a992...` TileLang commit build

Current corrected environment work
- clean clone: `tile-ai/TileOPs` `main` at `c39d65d31ea3cbd12261d55827ee81fc387dd174`
- Python: `3.12.12`
- torch: `2.10.0+cu128`
- `torch.version.cuda == 12.8`
- apache-tvm-ffi: `0.1.8.post2`
- tilelang: `0.1.8+cuda.gitded6a992`

How the pinned TileLang commit was installed
- direct `pip install tilelang==0.1.8 --no-deps` is not sufficient because it installs the release wheel, not the desired commit
- the requested commit was built from source into a wheel, then installed into the venv
- working high-level procedure:
  1. install `torch==2.10.0` from the `cu128` index
  2. install the non-torch Python deps (`apache-tvm-ffi==0.1.8.post2`, `cloudpickle`, `ml-dtypes`, `numpy`, `psutil`, `tqdm`, `z3-solver==4.15.4.0`, `torch-c-dlpack-ext`, etc.)
  3. install build deps: `cmake`, `ninja`, `scikit-build-core`, `cython`, `patchelf`, `build`
  4. build TileLang wheel from commit `ded6a992218a5ec0dbb490128cb21aae7794cdb8`
  5. install the generated wheel: `tilelang-0.1.8+cuda.gitded6a992-cp38-abi3-linux_x86_64.whl`
  6. install TileOPs editable with `--no-deps`

Observed state in the pinned-commit env
- `pip show tilelang` -> `0.1.8+cuda.gitded6a992`
- `torch.cuda.is_available() == True`
- `torch.cuda.device_count() == 8`
- `torch.cuda.get_device_capability() == (9, 0)`

Focused validation already passing in the pinned-commit env
- `python -m pytest tests/test_compile.py -q` -> `3 passed`
- `python -m pytest tests/ops/test_gemm.py -q -k 'smoke-fp16-square'` -> `1 passed`

Additional note from the source build
- the TileLang source build emitted CMake messages about imported CUDA targets such as `CUDA::cuda_driver` / `CUDA::nvml`, but the build still completed successfully and produced a working wheel in this environment

Next step
- rerun the full TileOPs suite in the commit-pinned TileLang environment so the final broad-validation result is commit-accurate

**Comment by superAngGao** [comment]
Update after rerunning with the actually intended TileLang commit.

Using the pinned TileLang commit
- `ded6a992218a5ec0dbb490128cb21aae7794cdb8`
- installed as wheel version `tilelang-0.1.8+cuda.gitded6a992`

Status summary
- environment builds successfully
- `torch.cuda.is_available() == True`
- `torch.cuda.get_device_capability() == (9, 0)`
- `tests/test_compile.py` passes (`3 passed`)
- `tests/ops/test_gemm.py -k 'smoke-fp16-square'` passes (`1 passed`)
- but broad validation does **not** currently match the earlier release-wheel full-suite result

First failing full-suite case in the pinned-commit env
- command used: `TMPDIR=$PWD/.tmp python -m pytest tests -x -vv`
- first failure:
  - `tests/ops/attention/test_deepseek_dsa_decode.py::test_sparse_mla_decode[1-128-1024-2048-512-64-2048-1-1-1024-None-dtype0-False]`
- failure mode:
  - not a CUDA init/runtime compatibility error
  - correctness mismatch versus reference output
  - `33152093 / 67108864` elements mismatched (`49.4%`)
  - greatest absolute difference: `0.19970703125`

Interpretation
- the earlier `2247 passed, 22 skipped` full-suite result applies to the clean env with the `tilelang==0.1.8` release wheel
- it does **not** apply to the pinned TileLang commit `ded6a992...`
- for the pinned commit, the environment itself is healthy, but broad correctness diverges at least on DeepSeek DSA decode very early in the suite

**Comment by superAngGao** [comment]
Update from Apr 18-19 local validation on the TileLang `5f70374c` validation env.

A useful milestone: after isolating a couple of device-poisoning kernels, the full suite now completes without the previous mass `ERROR` cascade. We are no longer blocked on generic suite-wide CUDA fallout before we can see real per-op failures.

Context
- The original local validation venv had `tilelang==0.1.8+cuda.gitded6a992`, which did not expose `wgmma_gemm` and could not run the current anchor/WS repro path.
- I aligned that environment to the external working TileLang build `0.1.8+cuda.git5f70374c` so the anchor path and API surface matched the known-good outside env.
- I also used a short writable temp dir (`TMPDIR=/home/ga/tltmp`) to avoid separate NVCC temp-path noise.

What we isolated
1. `tests/ops/test_gated_deltanet_recurrence.py`
- `fp32` is OK in isolation.
- `fp16` / `bf16` decode hit `CUDALaunch CUDA_ERROR_LAUNCH_FAILED` in isolation.
- In the full run, this was the first major device-poisoning source and caused the earlier `torch.manual_seed()` / `CUDA error: unspecified launch failure` cascade.

2. `tests/ops/test_gla_recurrence.py`
- `fp32` decode/multi-step do not launch-fail, but they produce all-`NaN` outputs in isolation.
- `fp16` / `bf16` decode also hit `CUDALaunch CUDA_ERROR_LAUNCH_FAILED` in isolation.
- After the first gated-deltanet isolation, this became the next device-poisoning source in the full run.

Temporary experiment used to expose the real remaining failures
- Temporarily skipped low-precision (`fp16` / `bf16`) cases in both recurrence files.
- With those skips plus the short `TMPDIR`, the full suite completed cleanly:
  - `51 failed, 2180 passed, 38 skipped, 16 warnings in 1:13:46`
  - importantly: `0 ERROR`

Interpretation
- At this point, the earlier mass `ERROR` behavior is not best explained by a generic suite-wide CUDA/PyTorch init failure anymore.
- After syncing the TileLang build and isolating the two recurrence kernels above, the environment is usable enough to surface concrete operator regressions.
- That means the remaining failures are much more actionable as real incompatibilities / regressions rather than broad runtime noise.

Main remaining failure buckets now visible
- attention decode / backward correctness failures (`deepseek_*`, `gqa*`, `mha*`)
- legacy TileLang API usage in `deepseek_dsa_decode` (`T.gemm(..., wg_wait=...)` no longer accepted by the current TileLang API surface)
- TVM / TileLang compile issues in `rope` and `mhc_pre`
- independent `convolution` and `fp8` failures

So the current picture seems to be:
- broad validation was initially obscured by real device-poisoning recurrence kernels
- after isolating those, the upgraded env is capable of running the suite to completion
- the next work should focus on the concrete remaining failure buckets rather than treating the whole env as universally broken

**Comment by superAngGao** [comment]
Closing as superseded by the TileLang 0.1.9 migration tracking issue #1039. The 5f70374c line was an intermediate validation target; remaining skips and restoration work are now summarized under #1039.
